[chore]: Do exit 0, and better error message

diff --git a/k8s/scope/networking/dns/get_hosted_zones b/k8s/scope/networking/dns/get_hosted_zones
--- a/k8s/scope/networking/dns/get_hosted_zones
+++ b/k8s/scope/networking/dns/get_hosted_zones
@@ -9,8 +9,8 @@ echo "Private Hosted Zone ID: $HOSTED_PRIVATE_ZONE_ID"
 
 # Check if both hosted zones are empty or null
 if [[ -z "$HOSTED_PUBLIC_ZONE_ID" || "$HOSTED_PUBLIC_ZONE_ID" == "null" ]] && [[ -z "$HOSTED_PRIVATE_ZONE_ID" || "$HOSTED_PRIVATE_ZONE_ID" == "null" ]]; then
-    echo "WARNING: Unable to find any hosted zones (neither public nor private)" >&2
-    exit 1
+    echo "Unable to find any hosted zones (neither public nor private)" >&2
+    exit 0
 fi
 
 export HOSTED_PUBLIC_ZONE_ID
