Add latest applications code

diff --git a/application/scripts/code-repo/generate_secrets b/application/scripts/code-repo/generate_secrets
--- a/application/scripts/code-repo/generate_secrets
+++ b/application/scripts/code-repo/generate_secrets
@@ -3,8 +3,7 @@ CI_ROLE_ID=1855672260
 # TODO(federico.maleh) missing support for mono repo
 # TODO(federico.maleh) missing support for extra secrets
 # TODO(federico.maleh) missing support for extra roles in api key
-# TODO(federico.maleh) missing add collaborators
-
+  
 API_KEY_NAME="ci-$NAMESPACE_SLUG-$NAMESPACE_ID-$APPLICATION_SLUG-$APPLICATION_ID"
 
 echo "Creating api key for ci: $API_KEY_NAME"
@@ -18,8 +17,16 @@ API_KEY_BODY=$(jq -nc \
 API_KEY_RESPONSE=$(np api-key create --format json --body "$API_KEY_BODY")
 
 API_KEY=$(echo "$API_KEY_RESPONSE" | jq -r .api_key)
+API_KEY_ID=$(echo "$API_KEY_RESPONSE" | jq -r .id)
 
-echo "Created api key for ci"
+if [[ -n "$API_KEY_ID" ]]; then
+  echo "Created ci api key: $API_KEY_ID"
+else
+  echo "Error creating ci api key"
+  echo "$API_API_KEY_RESPONSE" | jq
+
+  exit 1
+fi
 
 CODE_REPOSITORY_SECRETS="{\"NP_API_KEY\": \"$API_KEY\"}"
 
