Release 1.5.0 (#70)
* [feature]: Added support for external DNS using dns endpoint

* [feature]: waiting on balancer recognition for route

* [chore]: rename dns type to 'external_dns' in mninus

* [chore]: revert values.yaml

* [chore]: get information from providers for gateways

* [chore]: rework, we now apply the dns ednpoint only on scope creation

* [chore]: rework, we now apply the dns ednpoint only on scope creation

* [chore]: pr review

* [feature] define a component name with maximum 63 characters based on namespace and application slug

* feat: log improvements (#58)

* [fixes][route53]: we create the record on both hosted zones

* [feature] ignore not found errors when deleting k8s objects

* [feature] set default memory to 128 MB

* [feature] Add missing labels to k8s objects + Allow to delete extra gPRC ports (#68)

* [feature] Add missing labels to k8s objects

* [feature] add script to delete all objects related to a deployment_id

* feat: add Pod Disruption Budget (PDB) support (#64)

* feat: add Pod Disruption Budget (PDB) support

- Add POD_DISRUPTION_BUDGET configuration to values.yaml
- Integrate PDB settings into deployment build_context using jq
- Create pdb.yaml.tpl template with standard annotations and labels
- Support for configurable maxUnavailable (percentage or number)

* [feature]: pod disruption budget build tpl

* [feature]: private and public domains (#65)

* [feature] add support for web sockets inbound traffic (#69)

---------

Co-authored-by: Sebastian Nallar <sebastiansaidnallar@gmail.com>
Co-authored-by: Sebastian Nallar <95891104+sebasnallar@users.noreply.github.com>
Co-authored-by: Javi <javier.solis@nullplatform.io>

diff --git a/k8s/deployment/build_deployment b/k8s/deployment/build_deployment
--- a/k8s/deployment/build_deployment
+++ b/k8s/deployment/build_deployment
@@ -42,6 +42,7 @@ DEPLOYMENT_PATH="$OUTPUT_DIR/deployment-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
 SECRET_PATH="$OUTPUT_DIR/secret-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
 SCALING_PATH="$OUTPUT_DIR/scaling-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
 SERVICE_TEMPLATE_PATH="$OUTPUT_DIR/service-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
+PDB_PATH="$OUTPUT_DIR/pdb-$SCOPE_ID-$DEPLOYMENT_ID.yaml"
 CONTEXT_PATH="$OUTPUT_DIR/context-$SCOPE_ID.json"
 
 echo "$CONTEXT" | jq --arg replicas "$REPLICAS" --arg service_account_name "$SERVICE_ACCOUNT_NAME" '. + {replicas: $replicas, service_account_name: $service_account_name}' > "$CONTEXT_PATH"
@@ -94,7 +95,20 @@ gomplate -c .="$CONTEXT_PATH" \
 TEMPLATE_GENERATION_STATUS=$?
 
 if [[ $TEMPLATE_GENERATION_STATUS -ne 0 ]]; then
-    echo "Error building scaling template"
+    echo "Error building service template"
+    exit 1
+fi
+
+echo "Building Template: $PDB_TEMPLATE to $PDB_PATH"
+
+gomplate -c .="$CONTEXT_PATH" \
+  --file "$PDB_TEMPLATE" \
+  --out "$PDB_PATH"
+
+TEMPLATE_GENERATION_STATUS=$?
+
+if [[ $TEMPLATE_GENERATION_STATUS -ne 0 ]]; then
+    echo "Error building PDB template"
     exit 1
 fi
 
